datasource:
  url: jdbc:postgresql://localhost:8432/blog-db
  username: user
  password: password
  driver-class-name: org.postgresql.Driver

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  hbm2ddl-auto: update